### ISSUE TITLE
Extract Javascript & custom CSS from HTML pages

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/SourcePortal#4]
### Objective
There is Javascript and custom CSS in the HTML pages. This should be removed and replaced with <script> and CSS classes.
This will make #3 & #8 much easier.

### Information
There should be no `<script></script>` or `style=""` in the HTML once this is complete.
Only `<script src=""></script>` and `class=""`.

**Comment by chess-equality** [comment]
@BFergerson There are no more `<script></script>` blocks; all have been replaced with `<script src="">`.

As for the custom CSS, are they to be moved to classes in `css/style.css` and `css/dark_style.css`?

**Comment by BFergerson** [comment]
@chess-equality, I said there is no more custom JavaScript in my comment above. This issue is just about removing style attributes for CSS classes. Yes, move them into `style.css`.

**Comment by chess-equality** [comment]
@BFergerson I did some changes and then I stashed them, but now the graph doesn't show. Would you have an idea why? Stashing should've reset the changes to the working original.

**Comment by BFergerson** [comment]
@chess-equality, the portal may have expired. Try creating a new one (https://github.com/sourceplusplus/SourcePortal/issues/7#issue-680477362)

**Comment by BFergerson** [comment]
@chess-equality, nvm. It happens for me too. The server the portal is running on might be down. I'll reboot and let you know when it's back up.

**Comment by chess-equality** [comment]
@BFergerson Thanks, yes I'm always creating a new one.

`overview.html?requires_registration=true&artifact_qualified_name=LoopAdder.calculateSum()&app_uuid=24e92339-8770-4a0c-bef7-67e7b847f13e`

**Comment by BFergerson** [comment]
@chess-equality, should be back up.

**Comment by chess-equality** [comment]
@BFergerson I think the server is down again, I'm not getting any data.

**Comment by BFergerson** [comment]
@chess-equality, I've upgraded the server. Should go down less.
