### ISSUE TITLE
Build basic Vert.x server

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/SourcePortal#6]
### Objective
Build a basic Vert.x server that can serve the Overview/Traces/Configuration pages

### Information
This should be a fairly simple task. I think it just needs to have three GET routes that serve the HTML/JS code. This should be done before #3 since a server will be needed to serve the kotlinx.html version.

You should be able to hit `localhost:8080/overview`, `localhost:8080/traces`, `localhost:8080/configuration` and get the same pages as in #7.

**Comment by chess-equality** [comment]
@BFergerson I am working on this. My working branch is:

https://github.com/chess-equality/SourcePortal/tree/feature/issue-6/build-basic-vertx-server

**Comment by BFergerson** [comment]
Okay, for this a decent example for a basic server: https://github.com/vert-x3/vertx-examples/blob/a375c0726dcaf1ca9708f4f71e89a00647b6f09b/kotlin-examples/coroutines/src/main/kotlin/movierating/App.kt#L54

I like that the routing does not contain logic but just points to where the logic is, ie:
```kotlin
    router.get("/movie/:id").coroutineHandler { ctx -> getMovie(ctx) }
    router.post("/rateMovie/:id").coroutineHandler { ctx -> rateMovie(ctx) }
    router.get("/getRating/:id").coroutineHandler { ctx -> getRating(ctx) }
```

There won't be much in those handlers for now since you'll just be serving static HTML, but you'll need to expand on them for #3 so you might as well start setting up for that. 

Also, you can use PortalServer as the entry point. You can delete any commented code I add. That goes for commented code anywhere. It's just me testing stuff that I don't want to lose so I comment and commit. Once it's in the git history I don't care if you delete it.
