### ISSUE TITLE
Micro templating

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/SourcePortal#8]
https://github.com/flqw/spring-boot-kotlinx-html
https://github.com/kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing

Should be able to break UI down into various components:
 - Sidebar
 - Navbar
 - Area chart (throughput, resp time, sla)
 - Time Dropdown
 - Trace table
 - Trace stack table
 - Trace span table
 - Trace Dropdown
 - Artifact configuration
 - Artifact information

If things are broken down into components then something like this would be possible:
```kotlin
fun renderPage() : String {
    return createHTML().portal {
        overviewPage {
            sidebar {
                tabs { OVERVIEW, TRACES(LATEST,FAILED,SLOWEST), CONFIGURATION }
            }
            navbar {
                timeDropdown(5_MIN, 15_MIN, ...) { }
            }
            areaChart(AVG_THROUGHPUT, ....) { }
        }
    }
}
```

That's a really rough idea but the point is that when it comes to actually building the page for rendering that you don't use much (if any) CSS/HTML and rather everything has been made as a configurable component.

**Comment by chess-equality** [comment]
@BFergerson Should I do this next?

**Comment by BFergerson** [comment]
@chess-equality, please use https://github.com/sourceplusplus/SourcePortal/milestone/1 for ordering. #4 is next.

**Comment by chess-equality** [comment]
@BFergerson I'm working on this.

**Comment by BFergerson** [comment]
@chess-equality, please keep me updated and remember to commit early and commit often. We will likely need to discuss things as you work on this.

**Comment by chess-equality** [comment]
@BFergerson Ok.

**Comment by chess-equality** [comment]
@BFergerson I think the server is down again. Is it possible if I can restart it moving forward?

**Comment by BFergerson** [comment]
@chess-equality, it's back up. I am working on a way for you to be able to run everything locally through Docker. Till then just keep letting me know when it goes down. Hopefully, it isn't slowing you down too much.

**Comment by chess-equality** [comment]
@BFergerson I'm getting data but the chart is not showing both in Chrome and FF. Just merged the latest commits, haven't edited something yet.

**Comment by chess-equality** [comment]
@BFergerson I used my #4 branch, now the chart is showing. I guess some css got affected along the way. By the way I'm using incognito + disable cache in both Chrome and FF.

https://github.com/chess-equality/SourcePortal/tree/feature/issue-4/extract-custom-css

**Comment by BFergerson** [comment]
@chess-equality, make sure you're running the latest master branch. That is what I tested with and it works.

**Comment by chess-equality** [comment]
@BFergerson I'm running this branch, it's up to date with master:

https://github.com/chess-equality/SourcePortal/tree/feature/issue-8/micro-templating

**Comment by BFergerson** [comment]
@chess-equality, I've tested the master branch on Firefox/Chrome on Ubuntu/Windows. No issues. Try deleting the "build" directory and rebuilding the project followed by a hard refresh in the browser.

**Comment by chess-equality** [comment]
@BFergerson The `server/build` directory?

**Comment by BFergerson** [comment]
@chess-equality, any/every build directory. or './gradlew clean'

**Comment by chess-equality** [comment]
> Try deleting the "build" directory and rebuilding the project followed by a hard refresh in the browser.

@BFergerson The chart is still not showing. Do you want to check via TeamViewer?

**Comment by BFergerson** [comment]
@chess-equality, check chat.

**Comment by chess-equality** [comment]
@BFergerson I think the server is down again. Thanks.

**Comment by BFergerson** [comment]
@chess-equality, sorry, forgot to upgrade the server. Upgraded and rebooted.

**Comment by chess-equality** [comment]
> @chess-equality, sorry, forgot to upgrade the server. Upgraded and rebooted.

@BFergerson Thanks.

Could you please review the code so far:
https://github.com/chess-equality/SourcePortal/tree/feature/issue-8/micro-templating

**Comment by BFergerson** [comment]
Looking good so far but you need to open a PR for me to comment on specific code. (you can open it as a draft PR)

**Comment by chess-equality** [comment]
@BFergerson I think the server is down again, I'm not getting any data.

**Comment by BFergerson** [comment]
@chess-equality, I'll set up a cron to restart the server daily. We will be moving past this way of getting data in a few weeks.

**Comment by chess-equality** [comment]
@BFergerson Server down.

**Comment by BFergerson** [comment]
@chess-equality, it's back up.
